version: '3.9'

services:
    mod_redis:
        image: redis
        volumes:
            - ./mod_redis:/data
        stdin_open: true
        tty: true
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            network:
                ipv4_address: 172.16.1.3
    mod_manager:
        image: aivpn_mod_manager:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./config:/code/config/:ro
            - ./common:/code/common/
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mod_redis
        networks:
            network:
                ipv4_address: 172.16.1.4
    mod_comm_recv:
        image: aivpn_mod_comm_recv:latest
        volumes:
            - ./logs:/logs/
            - ./common:/code/common/:ro
            - ./config:/code/config/:ro
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mod_redis
            - mod_manager
        networks:
            network:
                ipv4_address: 172.16.1.5
    mod_comm_send:
        image: aivpn_mod_comm_send:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./config:/code/config/:ro
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mod_redis
            - mod_manager
        networks:
            network:
                ipv4_address: 172.16.1.6
    mod_report:
        image: aivpn_mod_report:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./config:/code/config/:ro
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mod_redis
            - mod_manager
        networks:
            network:
                ipv4_address: 172.16.1.7
    mod_slips:
        image: aivpn_mod_slips:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./config:/code/config/:ro
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - mod_redis
            - mod_manager
        networks:
            network:
                ipv4_address: 172.16.1.8
    mod_openvpn:
        privileged: true
        image: aivpn_mod_openvpn:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./data/conf_openvpn:/etc/openvpn
            - ./config:/code/config/:ro
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - "1194:1194/tcp"
        depends_on:
            - mod_redis
            - mod_manager
        networks:
            network:
                ipv4_address: 172.16.1.9
    mod_wireguard:
        image: aivpn_mod_wireguard:latest
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./data/conf_wireguard:/config
            - ./config:/code/config/:ro
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            - PUID=$ENV_PUID
            - PGID=$ENV_PGID
            - TZ=$ENV_TZ
            - SERVERURL=$ENV_SERVERURL
            - SERVERPORT=$ENV_SERVERPORT
            - PEERS=1
            - PEERDNS=$ENV_PEERDNS
            - INTERNAL_SUBNET=$ENV_INTERNAL_SUBNET
            - ALLOWEDIPS=$ENV_ALLOWEDIPS
        ports:
            - "1194:51820/udp"
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        depends_on:
            - mod_redis
            - mod_manager
        networks:
            network:
                ipv4_address: 172.16.1.10
    mod_novpn:
        privileged: true
        image: aivpn_mod_novpn:latest
        volumes:
            - ./logs:/logs/
            - ./data:/data/
            - ./data/conf_novpn:/etc/openvpn
            - ./config:/code/config/:ro
            - ./common:/code/common/:ro
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - "80:1194/tcp"
        depends_on:
            - mod_redis
            - mod_manager
        networks:
            network:
                ipv4_address: 172.16.1.11
    mod_pihole:
        image: pihole/pihole:latest
        ports:
            - "5900:80/tcp"
        environment:
            TZ: 'Europe/Prague'
        volumes:
            - './data/conf_pihole:/etc/pihole/'
            - './data/conf_pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        cap_add:
            - NET_ADMIN
        deploy:
            restart_policy:
                condition: on-failure
        depends_on: 
            - mod_redis
            - mod_manager
            - mod_openvpn
            - mod_wireguard
            - mod_novpn
        networks:
            network:
                ipv4_address: 172.16.1.2

volumes:
    mod_manager:
    mod_report:
    mod_slips:
    mod_redis:
    mod_comm_send:
    mod_comm_recv:
    mod_openvpn:
    mod_wireguard:
    mod_novpn:
    mod_pihole:

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.1/24
